// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUV6drZh-pa5wKfluENRxLZogNtADk-Dw',
    appId: '1:810602367788:android:f6818bbfe96e2d93b9ba89',
    messagingSenderId: '810602367788',
    projectId: 'store-commerce-shop',
    storageBucket: 'store-commerce-shop.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtYMIKQwDR0HbDHPUoC89pbhxmLmZtZR0',
    appId: '1:810602367788:ios:f343866956c95541b9ba89',
    messagingSenderId: '810602367788',
    projectId: 'store-commerce-shop',
    storageBucket: 'store-commerce-shop.appspot.com',
    iosBundleId: 'com.example.storeCommerceShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtYMIKQwDR0HbDHPUoC89pbhxmLmZtZR0',
    appId: '1:810602367788:ios:a2b44812c9294ad0b9ba89',
    messagingSenderId: '810602367788',
    projectId: 'store-commerce-shop',
    storageBucket: 'store-commerce-shop.appspot.com',
    iosBundleId: 'com.example.storeCommerceShop.RunnerTests',
  );
}
